Map<String, String> enLang = {
  'app_name': 'DOC\nMASTER',
  'continue_with': 'Continue With English',
  'choose_your_language': 'Choose your preferred language',
  'skip_now': 'Skip Now',
  'find_your_lost_document': 'Find your lost document',
  'lost_doucument_desc': 'When you lose documents, the Doc Master app uploads them and will let you know if another person uploads them as well as how to retrieve your lost documents.',
  'signup' : 'Sign Up',
  'signup_desc' : 'Sign up your account provide username, some basic information, and payment details',
  'login' : 'Log In',
  'login_desc' : 'Using your username/email address and password, log in to your account',
  'username_and_password' : 'Username and Password',
  'step1/3' : 'Step 1/3',
  'username' : 'Username',
  'password' : 'Password',
  'confirm_password' : 'Confirm Password',
  'password_desc' : 'The password must be at least 8 characters long and contain characters from alphabets, numbers,\nand special symbols.',
  'next_step' : 'Next Step',
  'already' : 'Already',
  'have_an_account' : 'have an account?',
  "dont" : "Don't",
  'forgot' : 'Forgot',
  'or' : 'or',

};
