Map<String, String> esLang = {
  'app_name': 'DOC\nMASTER',
  'continue_with': 'continuar con español',
  'choose_your_language': 'Elige tu idioma preferido',
  'skip_now': 'Saltar ahora',
  'find_your_lost_document': 'Encuentra tu documento perdido',
  'lost_doucument_desc': 'Cuando pierde documentos, la aplicación Doc Master los carga y le informará si otra persona los carga y le informará cómo recuperar sus documentos perdidos.',
  'signup' : 'Inscribirse',
  'signup_desc' : 'Registre su cuenta y proporcione el nombre de usuario, información básica y detalles de pago.',
  'login' : 'Acceso',
  'username_and_password' : 'Nombre de usuario y contraseña',
  'step1/3' : 'Paso 1/3',
  'username' : 'Nombre de usuario',
  'password' : 'Contraseña',
  'confirm_password' : 'confirmar Contraseña',
  'password_desc' : 'La contraseña debe tener al menos 8 caracteres y contener caracteres del alfabeto, números y símbolos especiales.',
  'next_step' : 'Próximo paso',
  'already' : 'Ya',
  'have_an_account' : '¿tener una cuenta?',
  "dont" : "No",
  'forgot' : 'Olvidó',
  'or' : 'o',
};