
Map<String, String> frLang = {
'app_name': 'DOC\nMASTER',
'continue_with': 'continuer avec le français',
  'choose_your_language': 'Choisissez votre langue préférée',
  'skip_now': 'Passer maintenant',
  'find_your_lost_document': 'Retrouvez votre document perdu',
  'lost_doucument_desc': "Lorsque vous perdez des documents, l'application Doc Master les télécharge et vous indiquera si une autre personne les télécharge ainsi que comment récupérer vos documents perdus.",
  'signup' : "S'inscrire",
  'signup_desc' : "Inscrivez-vous à votre compte, fournissez votre nom d'utilisateur, quelques informations de base et les détails de paiement",
  'login' : 'Se connecter',
  'username_and_password' : "Nom d'utilisateur et mot de passe",
  'step1/3' : 'Étape 1/3',
  'username' : "Nom d'utilisateur",
  'password' : 'Mot de passe',
  'confirm_password' : 'Confirmez le mot de passe',
  'password_desc' : 'Le mot de passe doit comporter au moins 8 caractères et contenir des caractères alphabétiques, des chiffres et des symboles spéciaux.',
  'next_step' : "L'étape suivante",
  'already' : 'Déjà',
  'have_an_account' : 'avoir un compte?',
  "dont" : "Ne le faites pas",
  'forgot' : 'Oublié',
  'or' : 'ou',
};